// <auto-generated />
namespace EducationCourse.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EditedFiles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditedFiles));
        
        string IMigrationMetadata.Id
        {
            get { return "202012091535268_EditedFiles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
